NamelessMC v2 pre13 and README.md update
NamelessMC/Nameless pull request #2498
Opened 2021-11-20 09:52 UTC by PadowYT2

This is done because of NamelessMC/Documentation#1

**Note: If any updates needed, msg me on discord `PadowYT2#1148`**

2021-12-28 09:37 UTC, Aberdeener requested changes
A few minor changes, but above all, we need to decide if we even want to use your new documentation software.
My vote is to stay with Wiki.js

2021-12-28 09:37 UTC, Aberdeener commented on .gitignore
> +/.github/
The `.github/` folder is used for issue templates + GitHub Actions workflows. It cannot be ignored!

2021-12-28 09:37 UTC, Aberdeener commented on README.md
> -Feature requests can be posted on the [forum](https://namelessmc.com/forum/view/7-web-feature-requests/), and bugs can be reported in the [GitHub Issues](https://github.com/NamelessMC/Nameless/issues
Before we totally remove this link, we should get the ok from Sam, as I know he would like to keep the website somewhat involved.

2021-12-28 09:37 UTC, Aberdeener commented on README.md
> +* All [NamelessMC Translation contributors](https://github.com/NamelessMC/Nameless/CONTRIBUTORS.md).
Nitpick: I would swap the order of translation contributors and contributors links

2021-12-30 05:04 UTC, PadowYT2 commented
Uh oh, I accidently deleted a rep and not the branch

I've created a new pull request #2549

2021-12-30 05:04 UTC, closed without merging