OAuth registration/login!
NamelessMC/Nameless pull request #2570
Opened 2022-01-17 06:59 UTC by Aberdeener

Lots of work yet to do, but registration and login working

2022-01-18 17:09 UTC, zJerino commented
**Good work**

2022-01-18 21:27 UTC, Derkades commented on modules/Core/pages/user/oauth.php
> +            Session::flash('oauth_error', "Another NamelessMC user is already linked to that $provider_name account.");
translations!

2022-01-18 21:44 UTC, Aberdeener commented on modules/Core/pages/user/oauth.php
> +            Session::flash('oauth_error', "Another NamelessMC user is already linked to that $provider_name account.");
thanks, added to the Todo list

2022-01-25 10:54 UTC, PadowYT2 reviewed
Looks all great, also I've modified the [docs page](https://docs.namelessmc.com/en/oauth).
Also, why not making the OAuth methods to register too?

2022-01-25 16:59 UTC, Aberdeener commented
> Looks all great, also I've modified the [docs page](https://docs.namelessmc.com/en/oauth). Also, why not making the OAuth methods to register too? And what is the redirect url should be put?

Thanks so much for doing that!
The redirect URLs:
- `http://example.com/index.php?route=/login/oauth/&provider=<provider>`
- `http://example.com/index.php?route=/user/oauth/&provider=<provider>`
*where `<provider>` is "google" or "discord"*

I would like to add OAuth registration - but it brings a whole other layer of complexity and potential bugs.
If a user registers with OAuth, all we would do is get their email from the provider, and autofill that on the registration page - but this could get complicated with things like AuthMe configured.

I'm going to take another shot at it, but for the little convenience it brings (since they dont have to link the provider afterwards), I'm not sure it is totally worth it.

2022-01-25 18:00 UTC, partydragen requested changes

2022-01-25 18:00 UTC, partydragen commented on custom/templates/DefaultRevamp/user/oauth.tpl
> +{foreach $OAUTH_PROVIDERS as $provider_name => $provider_data}
Modal missing translation

2022-01-26 08:00 UTC, PadowYT2 commented
Is discord really working?
![a](https://cdn.padow.ru/XU5B)
![a](https://cdn.padow.ru/v35Q)
The url I'm getting:
`https://discord.com/oauth2/authorize?scope=identify%20email&state=8547128e5ab6e9e8341f66d293b05527&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Fdev.namelessmc.xyz%2Findex.php%3Froute%3D%2Flogin%2Foauth%2F%26provider%3Ddiscord&client_id=876678761582563338`

2022-02-01 22:23 UTC, Aberdeener commented on custom/templates/DefaultRevamp/user/oauth.tpl
> +{foreach $OAUTH_PROVIDERS as $provider_name => $provider_data}
Added

2022-02-01 22:24 UTC, merged