Quick Actions
NamelessMC/Nameless pull request #2576
Opened 2022-01-19 15:15 UTC by xHelloC

![image](https://user-images.githubusercontent.com/20935558/150159246-c3177777-24c9-4d15-8254-eb6848350339.png)

they suggest to add this feature, I have it implemented somehow but I know it can be done better so I'm posting at least the files I changed to make it work.

Thank you for the reply

2022-01-19 22:42 UTC, PadowYT2 requested changes
You did a lot of mistakes. Where? To pull request you should use the **latest** version and not v2 pre12. You overwritted many wrong things.

*wrong review button, must be comment*

2022-01-20 07:54 UTC, Aberdeener requested changes
Thanks for the PR, looks like something went wrong when you PRd though haha. Did you base it off pr12 code?

2022-01-20 07:54 UTC, Aberdeener commented on custom/languages/Czech/general.php
> +$language = array (
We are using the shorthand array format now :)

2022-01-20 07:54 UTC, Aberdeener commented on custom/languages/Czech/general.php
> +    'leaderboards' => 'Leaderboards',
Looks like a few language terms were changed back to English

2022-01-20 07:54 UTC, Aberdeener commented on custom/panel_templates/Default/template.php
> +            $this->addCSSFiles(array(
Again, shorthand array syntax please

2022-01-20 07:54 UTC, Aberdeener commented on custom/panel_templates/Default/template.php
> +        public function __construct($cache, $smarty, $language, $user, $pages) {
Not sure what happened here!
We are using typehints now, and you seem to have added an unused`$cache` variable...

2022-01-20 07:54 UTC, Aberdeener commented on custom/panel_templates/Default/template.php
> -                    case 'forum_settings':
Why was this removed?

2022-01-20 07:54 UTC, Aberdeener commented on modules/Core/pages/panel/users.php
> +Module::loadPage($user, $pages, $cache, $smarty, array($navigation, $cc_nav, $mod_nav), $widgets);
Please use shorthand array syntax + add back the last template variable

2022-01-20 07:54 UTC, Aberdeener commented on modules/Core/pages/panel/users.php
> +define('PAGE', 'panel');
We use `const` instead of `define(...)` where applicable. Please revert

2022-01-20 07:54 UTC, Aberdeener commented on modules/Core/queries/admin_users.php
> +$sortColumns = ['username' => 'username', 'nickname' => 'nickname', 'joined' => 'joined', 'quick_action' => 'quick_action'];
There is no column named `quick_action` in the `nl2_users` table. What does this do?

2022-01-20 07:54 UTC, Aberdeener commented on modules/Core/queries/admin_users.php
> +        $obj->quick_action = array('
Looks like the template files haven't been uploaded in this PR to show the quick actions :(
Any idea what happened to them?

2022-01-20 07:54 UTC, Aberdeener commented on modules/Core/queries/admin_users.php
> +        <a href="'.URL::build('/panel/user/' . Output::getClean($result->id)) .'" class="badge badge-info"> <i class="fas fa-info"> </i>
Would be great if `URL::build(...)` was used everywhere here.
Also, this HTML should be in a `.tpl` file so templates can change them as needed 😄

2022-01-20 07:54 UTC, Aberdeener commented on modules/Core/queries/admin_users.php
> +        'draw' => isset($_GET['draw']) ? intval($_GET['draw']) : 0,
Please use casting instead of the `intval(...)` function!

2022-01-20 07:57 UTC, xHelloC commented
Thats right i just use the pre-12 lemme do pull request again

2022-01-20 22:50 UTC, closed without merging

2022-01-20 22:50 UTC, xHelloC commented
I will prepare a new pull request, but of course I know there will be errors. so hopefully this will help you at least a little, I'm a beginner in php