Update Japanese Translation & Add missing translations
NamelessMC/Nameless pull request #2637
Opened 2022-03-21 10:29 UTC by ViaSnake

This pull request makes three major changes.

- Japanese translation has been updated.
- Missing translations were added to each language.
- After the original translation (EnglishUK or EnglishUS) has been updated, if the translation has not been updated, it has been replaced.

2022-03-21 20:15 UTC, Aberdeener requested changes
Thanks so much for this.
Looks like you used some sort of automation to do it? Would be curious to see how that works!
The downside to this is that some of the translations are overwritten - I've made comments to mark them, they all seem to be the session error message...

2022-03-21 20:15 UTC, Aberdeener commented on custom/languages/Czech/installer.php
> -    'session_doesnt_exist' => 'Nepodařilo se detekovat relaci. Pro správnou funkci Nameless je potřeba funkce ukládání relací. Zkuste to prosím znovu. Pokud chyba přetrvává, kontaktujte podporu vašeh
Why was this translation overwritten?

2022-03-21 20:15 UTC, Aberdeener commented on custom/languages/Chinese(Simplified)/installer.php
> -    'session_doesnt_exist' => '无法检测会话。若想使用 Nameless，您必须启用会话。请您再试一次，若此问题始终存在，请咨询您的网页提供商。'
Why was this translation overwritten?

2022-03-21 20:15 UTC, Aberdeener commented on custom/languages/Danish/installer.php
> -    'session_doesnt_exist' => 'Ikke i stand til at opdage session. Session gemning er et krav for at bruge Nameless. Prøv igen, og hvis problemet fortsætter, bedes du kontakte din webvært for støtte.
Why was this translation overwritten?

2022-03-21 20:15 UTC, Aberdeener commented on custom/languages/Dutch/installer.php
> -    'session_doesnt_exist' => 'Niet in staat om de sessie te detecteren. Sessies opslaan is een vereiste om Nameless te gebruiken. Probeer het opnieuw, en als het probleem blijft bestaan, neem dan co
Why was this translation overwritten?

2022-03-21 20:15 UTC, Aberdeener commented on custom/languages/SwedishSE/installer.php
> -    'session_doesnt_exist' => 'Det gick inte att upptäcka sessionen. Sessionsbesparingar är ett krav för att använda Nameless. Försök igen, och om problemet kvarstår, kontakta din webbhotell för supp
Why was this translation overwritten?

2022-03-23 09:15 UTC, ViaSnake commented
> Thanks so much for this. Looks like you used some sort of automation to do it? Would be curious to see how that works! The downside to this is that some of the translations are overwritten - I've made comments to mark them, they all seem to be the session error message...

Unfortunately all changes were made by myself. Therefore, I did not use any automation or tools.

As for `session_doesnt_exist`, I overwrite it if the translation has not been updated since 88b1b0d.
With this change, the user will see the untranslated string until the next time someone updates it. Instead, when someone updates the translation, they will easily notice that the string has changed.

For me, it is very helpful to know immediately that a string has been changed. However, not all users will benefit from this. If this change is undesirable, I will revert.

2022-03-25 20:33 UTC, Aberdeener commented
Ah ok, I understand!

Thank you so much for the PR as always

2022-03-25 20:33 UTC, merged