Handle OAuth2 errors properly
NamelessMC/Nameless pull request #2940
Opened 2022-07-23 19:52 UTC by supercrafter100

Closes #2926

2022-07-23 20:00 UTC, Aberdeener commented
Could this also handle the “invalid provider” and “no oauth method set” exceptions?

2022-07-24 11:39 UTC, partydragen commented on modules/Core/pages/oauth.php
> +    ErrorHandler::logWarning("No OAuth Zmethod set");
Why z

2022-07-24 11:41 UTC, supercrafter100 commented on modules/Core/pages/oauth.php
> +    ErrorHandler::logWarning("No OAuth Zmethod set");
shh

2022-07-25 16:08 UTC, Aberdeener requested changes

2022-07-25 16:08 UTC, Aberdeener commented on custom/languages/en_UK.json
> +    "general/oauth_failed": "Something went wrong while trying to login/register/link with your OAuth account. Please try again",
"Something went wrong while trying to use OAuth. Please try again."

2022-07-25 16:08 UTC, Aberdeener commented on modules/Core/pages/oauth.php
> +    ErrorHandler::logWarning('An error occurred while handling an oauth ' . Session::get('oauth_method') . ' request: ' . $e->getMessage());
"OAuth" please 😄

2022-07-25 17:16 UTC, Aberdeener approved these changes

2022-07-26 19:20 UTC, samerton approved these changes

2022-07-27 12:08 UTC, partydragen approved these changes

2022-07-27 19:29 UTC, merged