Add userGroupAdded and userGroupRemoved to discord webhook formatter
NamelessMC/Nameless pull request #2958
Opened 2022-08-02 07:52 UTC by DominikSLK

I added userGroupAdded and userGroupRemoved events to discord webhook formatter and fixed hardcoded New Announcement.

2022-08-02 10:46 UTC, partydragen requested changes

2022-08-02 10:46 UTC, partydragen commented on core/classes/Core/User.php
> +            'avatar_url' => AvatarSource::getAvatarFromUserData($this->data()),
You are missing the full url param, anyways you should use `$user->getAvatar(128, true),` instead

2022-08-02 10:46 UTC, partydragen commented on core/classes/Core/User.php
> +            'avatar_url' => AvatarSource::getAvatarFromUserData($this->data()),
same here as above

2022-08-02 11:38 UTC, partydragen approved these changes

2022-08-02 16:30 UTC, DominikSLK commented
🤔

2022-08-05 19:08 UTC, samerton approved these changes

2022-08-05 19:08 UTC, samerton commented
Thanks!

2022-08-05 19:09 UTC, merged