Actually handle OAuth errors
NamelessMC/Nameless pull request #3030
Opened 2022-08-15 19:55 UTC by supercrafter100

When previously accessing the oauth page directly, an error is still thrown. This PR will fix this.

2022-08-15 20:48 UTC, DominikSLK approved these changes, later dismissed

2022-08-15 21:04 UTC, Aberdeener requested changes

2022-08-15 21:04 UTC, Aberdeener commented on modules/Core/pages/oauth.php
> +    Session::flash('home_error', $language->get('general', 'oauth_failed'));
I think a different message here like "No OAuth data detected, ensure you are accessing this page via an OAuth redirect" would be more applicable than an error message

2022-08-16 13:42 UTC, Aberdeener approved these changes

2022-08-16 13:43 UTC, merged