Allow members to reset their avatar
NamelessMC/Nameless pull request #3100
Opened 2022-10-07 12:29 UTC by supercrafter100

This adds the option for users to reset their custom avatar. Closes #3042 though this should probably not be merged before a major release as this will contain breaking changes for front-end templates (the addition of the button)

2022-10-07 12:30 UTC, supercrafter100 commented
I also cleaned up the file a bit to get rid of so many nested if () {} else { if() {} } things. Else if exits

2022-10-13 19:48 UTC, samerton requested changes

2022-10-13 19:48 UTC, samerton commented on custom/templates/DefaultRevamp/user/settings.tpl
> +            <div class="ui segment">
Might be worth only showing this if the user actually has an avatar?

2022-10-13 19:56 UTC, supercrafter100 commented on custom/templates/DefaultRevamp/user/settings.tpl
> +            <div class="ui segment">
Yep that makes sense

2022-10-17 19:14 UTC, samerton approved these changes

2022-10-17 19:16 UTC, merged