Add Integrations settings system & Setting to turn off mc username requirement
NamelessMC/Nameless pull request #3109
Opened 2022-10-14 21:20 UTC by partydragen

Add integrations settings system like how widgets & templates settings work also added the requested feature to turn off minecraft username requirement on registration while keeping the minecraft integration enabled

Closes https://github.com/NamelessMC/Nameless/issues/3043

![minecraft](https://user-images.githubusercontent.com/9625439/195945829-222ce15f-3a7e-47df-94d9-6f2402e382f3.PNG)
![discord](https://user-images.githubusercontent.com/9625439/195945850-b339b46c-e30d-459b-b449-20f5c4a677a1.PNG)

2022-10-17 19:28 UTC, samerton submitted a review, later dismissed

2022-10-18 18:20 UTC, Aberdeener submitted a review, later dismissed

2022-10-18 18:37 UTC, supercrafter100 requested changes

2022-10-18 18:37 UTC, supercrafter100 commented on modules/Core/pages/panel/integrations.php
> +    if ($integration->getSettings() !== null && file_exists($integration->getSettings())) {
Wouldn't it make more sense to throw an error if the integration settings file doesn't exist? Rather than just silently ignoring it. I feel like this can cause some frustration for developers that forget it.  And the settings file should never be configured anyways if the file doesn't exist. This can result in unwanted behavior in case a file was not uploaded correctly

2022-10-18 19:29 UTC, partydragen commented on modules/Core/pages/panel/integrations.php
> +    if ($integration->getSettings() !== null && file_exists($integration->getSettings())) {
Done

2022-10-18 19:34 UTC, supercrafter100 approved these changes

2022-10-19 12:14 UTC, merged