Fixing the duplication error in messaging.php
NamelessMC/Nameless pull request #3257
Opened 2023-02-17 06:12 UTC by Knuvex

- Fixed issue where message content was duplicated on page refresh

2023-02-18 00:45 UTC, Aberdeener commented
Thanks for the PR!
Are you able to do a screenrecording of the bug before and after the change?

2023-02-18 19:44 UTC, Derkades commented
I will explain
- The browser does a POST request when submitting a form
- Nameless replies to that content with HTML
- The browser renders that HTML and shows it to the user. When the user refreshes, the browser has to do the previous request again, which in this case is a POST request. This is potentially unwanted, which is why browsers warn before doing this. However, users ignore warnings and the warning is ugly.

The fix is to do this instead:
- When receiving the POST request, instead of replying with HTML, reply with a redirect instead
- The browser does a second GET request, this time the proper HTML is returned
- Now, when refreshing, the browser will only reissue the second GET request which has no side-effects

2023-02-20 14:18 UTC, samerton requested changes
Thanks for this! Just a couple of small things left as comments

2023-02-20 14:18 UTC, samerton commented on modules/Core/pages/user/messaging.php
> +                    if ($_SERVER['REQUEST_METHOD'] === 'POST') {
There should be no need to do this check here as we'll already be within a POST request.

2023-02-20 14:18 UTC, samerton commented on modules/Core/pages/user/messaging.php
> +                       header('Location: ' . $_SERVER['REQUEST_URI']);
We can remove this line and the `exit;` afterwards and simply do the following:
```php
Redirect::to($_SERVER['REQUEST_URI']);
```

2023-03-18 14:18 UTC, closed without merging