Remove the v1 converter during installation
NamelessMC/Nameless pull request #3293
Opened 2023-03-28 21:31 UTC by PadowYT2

Due to https://canary.discord.com/channels/246705793066467328/434751012428054530/1090382131202633771

2023-03-28 21:32 UTC, Aberdeener commented on core/installation/steps/upgrade_perform.php
> -            $.post("?step=ajax_initialise&initialise=upgrade", {perform: "true"}, function(response) {
In the `ajax_initialise` file, there are more references and code that does the actual conversion - that should all be torn out too

2023-03-29 17:56 UTC, Aberdeener requested changes

2023-03-29 17:56 UTC, tadhgboyle commented on core/installation/installer.php
> +    $_SESSION['action'] = 'install';
These lines can be removed if we link directly to `requirements_validation` (see suggestion comment)

2023-03-29 17:56 UTC, Aberdeener commented on core/installation/installer.php
>                                  <a href="?do=install" class="ui small primary button">
```suggestion
                                <a href="?step=requirements_validation" class="ui small primary button">
```

2023-03-29 17:56 UTC, Aberdeener commented on core/installation/steps/ajax_initialise.php
>                  $_SESSION['site_initialized'] = true;
This `if` statement can be pulled into the `else` right above it just to remove a layer of indentation

2023-03-30 10:02 UTC, PadowYT2 commented on core/installation/installer.php
> +    $_SESSION['action'] = 'install';
But then what about
https://github.com/NamelessMC/Nameless/blob/4ce36c752e15f8f8b714eacde3f71264ecf9d063/core/installation/installer.php#L75-L78

and

https://github.com/NamelessMC/Nameless/blob/4ce36c752e15f8f8b714eacde3f71264ecf9d063/core/installation/steps/requirements_validation.php#L3-L7

2023-04-06 00:56 UTC, Aberdeener approved these changes

2023-04-06 00:57 UTC, merged